apiVersion: apps/v1
kind: Deployment
metadata:
  name: uporabniki-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uporabniki
  template:
    metadata:
      labels:
        app: uporabniki
    spec:
      containers:
      - image: sabinca97/slikauporabnik:2
        name: uporabniki
        imagePullPolicy: Always
        env:
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          value: jdbc:postgresql://ec2-54-208-233-243.compute-1.amazonaws.com/d373nd6ijuq04e
        - name: KUMULUZEE_DATASOURCES0_USERNAME
          value: axmsufdwudxpwn
        - name: KUMULUZEE_DATASOURCES0_PASSWORD
          value: 550d2e28f70ccc901a7500c35a50cce651b356d13af4b6862468a80ea257fe9c
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP



---

apiVersion: v1
kind: Service
metadata:
  name: uporabniki
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: server
  selector:
    app: uporabniki


#    kubectl create -f uporabniki-deployment.yaml
#  kubectl get services
#  kubectl get deployments